### ISSUE TITLE
Magit/diff colors

### ISSUE THREAD

**Issue by dakrone** [juba/color-theme-tangotango#11]
The magit colors are a little bit... jarring (see screenshot below), especially the white background

![screen shot 2015-02-02 at 12 04 26 pm](https://cloud.githubusercontent.com/assets/19060/6006917/bf5d9476-aad3-11e4-8284-005a0342edd0.png)

Would you be open to changing the colors? If so I would happily submit a pull request

**Comment by juba** [comment]
Yes, of course. If you find a better color scheme for this (which should clearly be possible), I'd happily merge it.

Thanks in advance !

**Comment by juba** [comment]
As theming has changed a lot with magit 2.1.0, I deleted any custom magit faces from tangotango, and let the default magit ones :

https://github.com/magit/magit/issues/1922

Let me now if you see any glitch or possible improvements.
