### ISSUE TITLE
Comparison to included tango theme?

### ISSUE THREAD

**Issue by cpitclaudel** [juba/color-theme-tangotango#12]
Hi there,

Tangotango looks very nice. Could you comment on how much it differs from the bundled tango/tango-dark themes in Emacs 24.5?

Thanks!

**Comment by juba** [comment]
I'm not sure I could really tell. I created `tangotango` in the beginning to add `org-mode` and `gnus` support, essentially. But for other modes there should not be many differences with other tango palette based themes...

**Comment by cpitclaudel** [comment]
Thanks!
