### ISSUE TITLE
white background for headings and tables

### ISSUE THREAD

**Issue by Hagopian** [juba/color-theme-tangotango#14]
I tried out your theme, but I'm not getting the supposed look, instead it looks like [this](http://www.haggiz.de/images/tangotango.jpg) I seem to get this for other themes as well, any idea why?
I'm using Scimax on Win7 and put this at the end of my user.el

;;color themes
(use-package color-theme
  :ensure t)
(require 'color-theme)
(add-to-list 'custom-theme-load-path "D:/000-nextcloud/Hagen/org-mode/color/")
(load-theme 'tangotango t)

**Comment by articuluxe** [comment]
You are mixing theme types. Assuming your emacs version is at least 24, you probably don’t want the color-theme package. Remove the use-package invocation and the require statement, which are redundant also, and try again.

**Comment by Hagopian** [comment]
I tried it, but that unfortunately does not change anything. I'm running 25.2. I also looked whether it is loaded elsewhere, but that does not seem to be the case.
Any other thoughts?

**Comment by articuluxe** [comment]
Are there any errors in the messages buffer?

Do other themes load correctly?  Try some of the built-in, leuven, etc.

**Comment by Hagopian** [comment]
That was actually a very good point, so loading leuven did not do anything. So I tried disable-theme and apparently 'leuven' was already loaded, so it is the standard theme on my installation together with 'smart-mode-line-light'. I could also find from where it was loaded and when I disable it there everything works as expected!
Thanks a lot!

**Comment by juba** [comment]
Cloding the issue. Thanks a lot @articuluxe for the solution !
