### ISSUE TITLE
Release new version to melpa

### ISSUE THREAD

**Issue by fapdash** [juba/color-theme-tangotango#20]
Hey there @juba,

can you please release a new version to melpa so I can use my change from https://github.com/juba/color-theme-tangotango/pull/19 via melpa?

**Comment by juba** [comment]
Hi,

Unfortunately I haven't use Emacs for a long time now. I've tried to take a quick look at how to update this theme on MELP but didn't find clear instructions. Would you have a link on how to proceed ?

Thanks !
